dist: bionic
install:
- travis_retry sudo apt-get install -y python sudo wget xxd
- pushd /tmp
- travis_retry wget https://deb.nodesource.com/setup_12.x -O /tmp/install-node.sh
- sudo sh /tmp/install-node.sh
- travis_retry sudo apt-get install -y nodejs
- travis_retry wget https://sdk.dfinity.org/install.sh -O /tmp/install-sdk.sh
- yes Y | sh /tmp/install-sdk.sh
- export PATH=/home/$USER/bin:$PATH
- popd
script:
- npm install
- dfx start --background
- sleep 5
- dfx build
- dfx canister install --all
- ID=$(xxd -p canisters/index/_canister.id)
- CRC=$(python -c "import crc8;h=crc8.crc8();h.update(\"$ID\".decode(\"hex\"));print(h.hexdigest())")
- wget http://127.0.0.1:8001/?canisterId=ic:$ID$CRC
- cat index.html
