dist: bionic
install:
- # Install DFINITY SDK.
- travis_retry wget https://sdk.dfinity.org/install.sh
- yes Y | sh install.sh
- # Install Google HTML Compressor.
- travis_retry wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/htmlcompressor/htmlcompressor-1.5.3.jar
- sudo mv htmlcompressor-1.5.3.jar /usr/share/java
- # Install Yahoo CSS and JavaScript Compressor.
- travis_retry wget https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar
- sudo mv yuicompressor-2.4.8.jar /usr/share/java
- # Install Nginx with Lua support.
- travis_retry sudo apt-get install --yes nginx libnginx-mod-http-lua
- sudo usermod -G adm -a $USER
- # Install Lua package manager.
- travis_retry sudo apt-get install --yes luarocks
- # Install Lua CBOR package.
- travis_retry sudo luarocks install org.conman.cbor
- # Install Lua Hex package.
- travis_retry sudo luarocks install hex
- # Install Lua OpenSSL package.
- travis_retry sudo apt-get install --yes libssl-dev
- travis_retry sudo luarocks install luaossl
- # Install Lua Socket package.
- travis_retry sudo luarocks install luasocket
script:
- nohup dfx start &
- sleep 5
- make
- make install
- sudo sg adm -c 'nohup nginx -c nginx.conf -p build/nginx &'
- wget 127.0.0.1:8000
- cat index.html
