dist: bionic
install:
- travis_retry sudo apt-get install -y bc curl git libssl-dev openjdk-8-jre sudo wget xxd
- # Navigate to temporary directory.
- pushd /tmp
- # Install Google HTML Compressor.
- travis_retry wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/htmlcompressor/htmlcompressor-1.5.3.jar
- sudo install htmlcompressor-1.5.3.jar /usr/share/java
- # Install Yahoo CSS and JavaScript Compressor.
- travis_retry wget https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar
- sudo install yuicompressor-2.4.8.jar /usr/share/java
- # Install Node.
- travis_retry wget https://deb.nodesource.com/setup_12.x -O /tmp/install.sh
- sudo sh /tmp/install.sh
- travis_retry sudo apt-get install -y nodejs
- # Install DFINITY SDK.
- travis_retry wget https://sdk.dfinity.org/install.sh -O /tmp/install.sh
- yes Y | sh /tmp/install.sh
- export PATH=/home/$USER/bin:$PATH
- # Install Nginx with Lua support.
- travis_retry sudo apt-get install -y nginx libnginx-mod-http-lua
- sudo chown $USER /var/log/nginx/error.log
- sudo bash -c 'mkdir /var/lib/nginx/{body,fastcgi,proxy,scgi,uwsgi}'
- # Install self-signed SSL certificate.
- openssl req -days 365 -keyout linkedup.key -newkey rsa:2048 -nodes -out linkedup.crt -subj '/C=US/ST=CA/L=San Francisco/O=DFINITY USA Research, LLC/OU=IT/CN=127.0.0.1' -x509
- sudo chmod 755 /etc/ssl/private
- sudo install linkedup.crt /etc/ssl/certs
- sudo install linkedup.key /etc/ssl/private
- # Install Lua package manager.
- travis_retry sudo apt-get install -y luarocks
- # Install Lua packages.
- travis_retry sudo luarocks install hex
- travis_retry sudo luarocks install luaossl
- travis_retry sudo luarocks install luasec
- travis_retry sudo luarocks install org.conman.cbor
- # Navigate to workspace directory.
- popd
script:
- nohup sh bootstrap.sh &
- wget --no-check-certificate https://127.0.0.1:8000
- cat index.html
